require: rubocop-rspec

AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Layout/LineLength:
  Max: 100
  IgnoredPatterns: ['\#.*'] # ignore long comments

Style/ParallelAssignment:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/LambdaCall:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Naming/MethodParameterName:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/BlockDelimiters:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Metrics/MethodLength:
  Max: 15

Style/AsciiComments:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

# Should always be configured:
Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

